### ISSUE TITLE
Plugin error: panic: interface conversion: interface {} is nil, not string

### ISSUE THREAD

**Issue by dushevadnqka** [site24x7/terraform-provider-site24x7#111]
Directly sharing the error trace:
```
The plugin encountered an error, and failed to respond to the plugin.(*GRPCProvider).ApplyResourceChange call. The plugin logs may contain more details.
╵

Stack trace from the terraform-provider-site24x7_v1.0.24 plugin:

panic: interface conversion: interface {} is nil, not string

goroutine 14 [running]:
github.com/site24x7/terraform-provider-site24x7/site24x7/monitors.resourceDataToWebsiteMonitor(0xc0001d8700, 0x1bff868, 0xc00009f0e0, 0x1bff868, 0xc00009f0e0, 0x0)
	github.com/site24x7/terraform-provider-site24x7/site24x7/monitors/website.go:544 +0x2c2d
github.com/site24x7/terraform-provider-site24x7/site24x7/monitors.websiteMonitorUpdate(0xc0001d8700, 0x1a65680, 0xc00009f0e0, 0x24, 0x2104bc0)
	github.com/site24x7/terraform-provider-site24x7/site24x7/monitors/website.go:395 +0x76
github.com/hashicorp/terraform-plugin-sdk/helper/schema.(*Resource).Apply(0xc00019ee00, 0xc000618190, 0xc0004c92a0, 0x1a65680, 0xc00009f0e0, 0x32a37365646f6301, 0x615f657375a83030, 0x657375a8c06e706c)
	github.com/hashicorp/terraform-plugin-sdk@v1.1.1/helper/schema/resource.go:311 +0x273
github.com/hashicorp/terraform-plugin-sdk/helper/schema.(*Provider).Apply(0xc00019f900, 0xc0005218e8, 0xc000618190, 0xc0004c92a0, 0xc0006d9ca8, 0xc0006e0018, 0x1989c60)
	github.com/hashicorp/terraform-plugin-sdk@v1.1.1/helper/schema/provider.go:294 +0x99
github.com/hashicorp/terraform-plugin-sdk/internal/helper/plugin.(*GRPCProviderServer).ApplyResourceChange(0xc00010ea30, 0x1bf3670, 0xc00046c660, 0xc000078780, 0xc00010ea30, 0xc00046c660, 0xc000720a50)
	github.com/hashicorp/terraform-plugin-sdk@v1.1.1/internal/helper/plugin/grpc_provider.go:885 +0x88b
github.com/hashicorp/terraform-plugin-sdk/internal/tfplugin5._Provider_ApplyResourceChange_Handler(0x1a5c020, 0xc00010ea30, 0x1bf3670, 0xc00046c660, 0xc000078720, 0x0, 0x1bf3670, 0xc00046c660, 0xc0004f4800, 0xae5)
	github.com/hashicorp/terraform-plugin-sdk@v1.1.1/internal/tfplugin5/tfplugin5.pb.go:3189 +0x214
google.golang.org/grpc.(*Server).processUnaryRPC(0xc000148000, 0x1bfb878, 0xc000113080, 0xc0005a6400, 0xc00007c6f0, 0x20c64e0, 0x0, 0x0, 0x0)
	google.golang.org/grpc@v1.23.0/server.go:995 +0x482
google.golang.org/grpc.(*Server).handleStream(0xc000148000, 0x1bfb878, 0xc000113080, 0xc0005a6400, 0x0)
	google.golang.org/grpc@v1.23.0/server.go:1275 +0xd2c
google.golang.org/grpc.(*Server).serveStreams.func1.1(0xc00044ef20, 0xc000148000, 0x1bfb878, 0xc000113080, 0xc0005a6400)
	google.golang.org/grpc@v1.23.0/server.go:710 +0xab
created by google.golang.org/grpc.(*Server).serveStreams.func1
	google.golang.org/grpc@v1.23.0/server.go:708 +0xa5

Error: The terraform-provider-site24x7_v1.0.24 plugin crashed!

This is always indicative of a bug within the plugin. It would be immensely
helpful if you could report the crash with the plugin's maintainers so that it
can be fixed. The output above should help diagnose the issue.
```

**Comment by jim-billy-zoho** [comment]
@dushevadnqka Can you please send us the configuration file to debug the issue?

**Comment by dushevadnqka** [comment]
@jim-billy-zoho ,
Sure thing:
```
resource "site24x7_website_monitor" "some_website_monitor" {
    ...
    ...
    ...
    tag_ids      = [
        each.value.env == "dev" ? var.my_tag.id : ""
    ]
}
```
I fixed the issue as avoided the empty string here: `each.value.env == "dev" ? var.my_tag.id : ""`

**Comment by jim-billy** [comment]
@dushevadnqka Have added empty string check for tag_ids in the latest release - 1.0.27.
