### ISSUE TITLE
1.0.55 - panic: interface conversion: interface {} is map[string]interface {}, not []interface {}

### ISSUE THREAD

**Issue by anthosz** [site24x7/terraform-provider-site24x7#190]
Hello,

Since 1.0.55, unable to plan something with the terraform provider (works once rollback to 1.0.54):
```
Stack trace from the terraform-provider-site24x7_v1.0.55 plugin:
panic: interface conversion: interface {} is map[string]interface {}, not []interface {}
goroutine 82 [running]:
github.com/site24x7/terraform-provider-site24x7/site24x7.setCommonResourceData(0xc000489420, 0xc00035cbe0)
	github.com/site24x7/terraform-provider-site24x7/site24x7/threshold_profile.go:599 +0x585
github.com/site24x7/terraform-provider-site24x7/site24x7.updateThresholdProfileResourceData(0xc000489420, 0xc00035cbe0)
	github.com/site24x7/terraform-provider-site24x7/site24x7/threshold_profile.go:438 +0x185
github.com/site24x7/terraform-provider-site24x7/site24x7.thresholdProfileRead(0xc000489420, 0xeaada0, 0xc0004f98e0, 0xc000489420, 0x0)
	github.com/site24x7/terraform-provider-site24x7/site24x7/threshold_profile.go:357 +0x105
github.com/hashicorp/terraform-plugin-sdk/helper/schema.(*Resource).RefreshWithoutUpgrade(0xc000127980, 0xc0001a7310, 0xeaada0, 0xc0004f98e0, 0xc0003c23b0, 0x0, 0x0)
	github.com/hashicorp/terraform-plugin-sdk@v1.1.1/helper/schema/resource.go:455 +0x12e
github.com/hashicorp/terraform-plugin-sdk/internal/helper/plugin.(*GRPCProviderServer).ReadResource(0xc00011a500, 0x1029130, 0xc000723200, 0xc0007260f0, 0xc00011a500, 0xc000743a50, 0x46ca67)
	github.com/hashicorp/terraform-plugin-sdk@v1.1.1/internal/helper/plugin/grpc_provider.go:525 +0x3dd
github.com/hashicorp/terraform-plugin-sdk/internal/tfplugin5._Provider_ReadResource_Handler(0xe8bbe0, 0xc00011a500, 0x1029130, 0xc000723200, 0xc0001887e0, 0x0, 0x1029130, 0xc000723200, 0xc000756000, 0x2e4)
	github.com/hashicorp/terraform-plugin-sdk@v1.1.1/internal/tfplugin5/tfplugin5.pb.go:3153 +0x214
google.golang.org/grpc.(*Server).processUnaryRPC(0xc000470160, 0x10313f8, 0xc000102f00, 0xc0002b0100, 0xc00021aa80, 0x1506390, 0x0, 0x0, 0x0)
	google.golang.org/grpc@v1.23.0/server.go:995 +0x482
google.golang.org/grpc.(*Server).handleStream(0xc000470160, 0x10313f8, 0xc000102f00, 0xc0002b0100, 0x0)
	google.golang.org/grpc@v1.23.0/server.go:1275 +0xd2c
google.golang.org/grpc.(*Server).serveStreams.func1.1(0xc000042250, 0xc000470160, 0x10313f8, 0xc000102f00, 0xc0002b0100)
	google.golang.org/grpc@v1.23.0/server.go:710 +0xab
created by google.golang.org/grpc.(*Server).serveStreams.func1
	google.golang.org/grpc@v1.23.0/server.go:708 +0xa5
Error: The terraform-provider-site24x7_v1.0.55 plugin crashed!
This is always indicative of a bug within the plugin. It would be immensely
helpful if you could report the crash with the plugin's maintainers so that it
can be fixed. The output above should help diagnose the issue.
```

```
resource "site24x7_threshold_profile" "XXXX" {
│ 
│ The plugin encountered an error, and failed to respond to the
│ plugin.(*GRPCProvider).ReadResource call. The plugin logs may contain more
│ details
```

Best regards,

**Comment by dil-ddecarvalhogomes** [comment]
+1
