### ISSUE TITLE
panic in terraform-provider-site24x7_v1.0.90 plugin

### ISSUE THREAD

**Issue by valugi** [site24x7/terraform-provider-site24x7#288]
```
The plugin encountered an error, and failed to respond to the plugin.(*GRPCProvider).ReadResource call. The plugin logs may contain more details.
╵
╷
│ Error: Plugin did not respond
│ 
│   with module.website.site24x7_website_monitor.website,
│   on .terraform/modules/website/main.tf line 1, in resource "site24x7_website_monitor" "website":
│    1: resource "site24x7_website_monitor" "website" {
│ 
│ The plugin encountered an error, and failed to respond to the plugin.(*GRPCProvider).ReadResource call. The plugin logs may contain more details.
╵

Stack trace from the terraform-provider-site24x7_v1.0.90 plugin:

panic: interface conversion: interface {} is nil, not string

goroutine 26 [running]:
github.com/site24x7/terraform-provider-site24x7/site24x7/monitors.updateDomainExpiryMonitorResourceData(0xc000134000, 0xc00037e2c0)
        github.com/site24x7/terraform-provider-site24x7/site24x7/monitors/domain_expiry.go:422 +0xf0d
github.com/site24x7/terraform-provider-site24x7/site24x7/monitors.domainExpiryMonitorRead(0xc000134000, 0x1aea8c0, 0xc00046a8e0, 0xc000134000, 0x0)
        github.com/site24x7/terraform-provider-site24x7/site24x7/monitors/domain_expiry.go:253 +0xf7
github.com/hashicorp/terraform-plugin-sdk/helper/schema.(*Resource).RefreshWithoutUpgrade(0xc000046c80, 0xc0000a4730, 0x1aea8c0, 0xc00046a8e0, 0xc00020a440, 0x0, 0x0)
        github.com/hashicorp/terraform-plugin-sdk@v1.1.1/helper/schema/resource.go:455 +0x12e
github.com/hashicorp/terraform-plugin-sdk/internal/helper/plugin.(*GRPCProviderServer).ReadResource(0xc0000c45a0, 0x1c67410, 0xc000548d80, 0xc0000a4640, 0xc0000c45a0, 0xc000548d80, 0xc000256a50)
        github.com/hashicorp/terraform-plugin-sdk@v1.1.1/internal/helper/plugin/grpc_provider.go:525 +0x3dd
github.com/hashicorp/terraform-plugin-sdk/internal/tfplugin5._Provider_ReadResource_Handler(0x1ac2c40, 0xc0000c45a0, 0x1c67410, 0xc000548d80, 0xc00070c120, 0x0, 0x1c67410, 0xc000548d80, 0xc00061a600, 0x2c7)
        github.com/hashicorp/terraform-plugin-sdk@v1.1.1/internal/tfplugin5/tfplugin5.pb.go:3153 +0x214
google.golang.org/grpc.(*Server).processUnaryRPC(0xc00037e160, 0x1c6fe18, 0xc000437080, 0xc00061e000, 0xc00013f350, 0x2159570, 0x0, 0x0, 0x0)
        google.golang.org/grpc@v1.23.0/server.go:995 +0x482
google.golang.org/grpc.(*Server).handleStream(0xc00037e160, 0x1c6fe18, 0xc000437080, 0xc00061e000, 0x0)
        google.golang.org/grpc@v1.23.0/server.go:1275 +0xd2c
google.golang.org/grpc.(*Server).serveStreams.func1.1(0xc0000ba750, 0xc00037e160, 0x1c6fe18, 0xc000437080, 0xc00061e000)
        google.golang.org/grpc@v1.23.0/server.go:710 +0xab
created by google.golang.org/grpc.(*Server).serveStreams.func1
        google.golang.org/grpc@v1.23.0/server.go:708 +0xa5

Error: The terraform-provider-site24x7_v1.0.90 plugin crashed!

This is always indicative of a bug within the plugin. It would be immensely
helpful if you could report the crash with the plugin's maintainers so that it
can be fixed. The output above should help diagnose the issue.
```

**Comment by sujithramagesh** [comment]
Hi,can you give the input which you have tried with?

**Comment by valugi** [comment]
I do not understand what do you mean by input.
Here is the terraform plan:

---
Terraform used the selected providers to generate the following execution plan. Resource actions are indicated with the following symbols:
  ~ update in-place

Terraform planned the following actions, but then encountered a problem:

  # module.oracle_credentials.site24x7_credential_profile.resource will be updated in-place
  ~ resource "site24x7_credential_profile" "resource" {
        id              = "396627000019969016"
      + password        = (sensitive value)
        # (3 unchanged attributes hidden)
    }

Plan: 0 to add, 1 to change, 0 to destroy.
╷
│ Error: Plugin did not respond
│ 
│   with module.envista_expiry.site24x7_domain_expiry_monitor.expiry_monitor,
│   on .terraform/modules/envista_expiry/main.tf line 1, in resource "site24x7_domain_expiry_monitor" "expiry_monitor":
│    1: resource "site24x7_domain_expiry_monitor" "expiry_monitor" {
│ 
│ The plugin encountered an error, and failed to respond to the plugin.(*GRPCProvider).ReadResource call. The plugin logs may contain more details.
╵
╷
│ Error: Plugin did not respond
│ 
│   with module.envista_website.site24x7_website_monitor.website,
│   on .terraform/modules/envista_website/main.tf line 1, in resource "site24x7_website_monitor" "website":
│    1: resource "site24x7_website_monitor" "website" {
│ 
│ The plugin encountered an error, and failed to respond to the plugin.(*GRPCProvider).ReadResource call. The plugin logs may contain more details.
╵
╷
│ Error: Plugin did not respond
│ 
│   with module.oracle.site24x7_rest_api_monitor.resource,
│   on .terraform/modules/oracle/main.tf line 1, in resource "site24x7_rest_api_monitor" "resource":
│    1: resource "site24x7_rest_api_monitor" "resource" {
│ 
│ The plugin encountered an error, and failed to respond to the plugin.(*GRPCProvider).ReadResource call. The plugin logs may contain more details.
╵
╷
│ Error: Plugin did not respond
│ 
│   with module.smile_website.site24x7_website_monitor.website,
│   on .terraform/modules/smile_website/main.tf line 1, in resource "site24x7_website_monitor" "website":
│    1: resource "site24x7_website_monitor" "website" {
│ 
│ The plugin encountered an error, and failed to respond to the plugin.(*GRPCProvider).ReadResource call. The plugin logs may contain more details.
╵

Stack trace from the terraform-provider-site24x7_v1.0.90 plugin:

panic: interface conversion: interface {} is nil, not string

goroutine 161 [running]:
github.com/site24x7/terraform-provider-site24x7/site24x7/monitors.updateDomainExpiryMonitorResourceData(0xc0002572d0, 0xc0007caf20)
	github.com/site24x7/terraform-provider-site24x7/site24x7/monitors/domain_expiry.go:422 +0xf0d
github.com/site24x7/terraform-provider-site24x7/site24x7/monitors.domainExpiryMonitorRead(0xc0002572d0, 0x1aea8c0, 0xc00064aff0, 0xc0002572d0, 0x0)
	github.com/site24x7/terraform-provider-site24x7/site24x7/monitors/domain_expiry.go:253 +0xf7
github.com/hashicorp/terraform-plugin-sdk/helper/schema.(*Resource).RefreshWithoutUpgrade(0xc00011b300, 0xc0008c40a0, 0x1aea8c0, 0xc00064aff0, 0xc00000e918, 0x0, 0x0)
	github.com/hashicorp/terraform-plugin-sdk@v1.1.1/helper/schema/resource.go:455 +0x12e
github.com/hashicorp/terraform-plugin-sdk/internal/helper/plugin.(*GRPCProviderServer).ReadResource(0xc000116468, 0x1c67410, 0xc000b10000, 0xc000b12000, 0xc000116468, 0xc000b0fa50, 0x106c667)
	github.com/hashicorp/terraform-plugin-sdk@v1.1.1/internal/helper/plugin/grpc_provider.go:525 +0x3dd
github.com/hashicorp/terraform-plugin-sdk/internal/tfplugin5._Provider_ReadResource_Handler(0x1ac2c40, 0xc000116468, 0x1c67410, 0xc000b10000, 0xc000114ba0, 0x0, 0x1c67410, 0xc000b10000, 0xc000364000, 0x2ca)
	github.com/hashicorp/terraform-plugin-sdk@v1.1.1/internal/tfplugin5/tfplugin5.pb.go:3153 +0x214
google.golang.org/grpc.(*Server).processUnaryRPC(0xc000468160, 0x1c6fe18, 0xc000225680, 0xc0007d0000, 0xc000202570, 0x2159570, 0x0, 0x0, 0x0)
	google.golang.org/grpc@v1.23.0/server.go:995 +0x482
google.golang.org/grpc.(*Server).handleStream(0xc000468160, 0x1c6fe18, 0xc000225680, 0xc0007d0000, 0x0)
	google.golang.org/grpc@v1.23.0/server.go:1275 +0xd2c
google.golang.org/grpc.(*Server).serveStreams.func1.1(0xc00021a170, 0xc000468160, 0x1c6fe18, 0xc000225680, 0xc0007d0000)
	google.golang.org/grpc@v1.23.0/server.go:710 +0xab
created by google.golang.org/grpc.(*Server).serveStreams.func1
	google.golang.org/grpc@v1.23.0/server.go:708 +0xa5

Error: The terraform-provider-site24x7_v1.0.90 plugin crashed!

This is always indicative of a bug within the plugin. It would be immensely
helpful if you could report the crash with the plugin's maintainers so that it
can be fixed. The output above should help diagnose the issue.
---
